data = [
    {"name": "Shah Rukh Khan", "description": "Actor", "country": "Mumbai", "followers_count": 47},
    {"name": "Virat Kohli", "description": "Cricketer", "country": "Delhi", "followers_count": 280},
    {"name": "Priyanka Chopra", "description": "Actress", "country": "Mumbai", "followers_count": 92},
    {"name": "Alia Bhatt", "description": "Actress", "country": "Mumbai", "followers_count": 90},
    {"name": "Deepika Padukone", "description": "Actress", "country": "Bengaluru", "followers_count": 80},
    {"name": "Salman Khan", "description": "Actor", "country": "Mumbai", "followers_count": 65},
    {"name": "Amitabh Bachchan", "description": "Actor", "country": "Mumbai", "followers_count": 40},
    {"name": "Katrina Kaif", "description": "Actress", "country": "London/Mumbai", "followers_count": 77},
    {"name": "Ranveer Singh", "description": "Actor", "country": "Mumbai", "followers_count": 47},
    {"name": "Hrithik Roshan", "description": "Actor", "country": "Mumbai", "followers_count": 47},
    {"name": "Sachin Tendulkar", "description": "Cricketer", "country": "Mumbai", "followers_count": 45},
    {"name": "MS Dhoni", "description": "Cricketer", "country": "Ranchi", "followers_count": 48},
    {"name": "Neha Kakkar", "description": "Singer", "country": "Rishikesh", "followers_count": 75},
    {"name": "Jacqueline Fernandez", "description": "Actress", "country": "Colombo/Mumbai", "followers_count": 70},
    {"name": "Sunny Leone", "description": "Actress", "country": "Canada/Mumbai", "followers_count": 60},
    {"name": "Anushka Sharma", "description": "Actress", "country": "Ayodhya/Mumbai", "followers_count": 65},
    {"name": "Akshay Kumar", "description": "Actor", "country": "Punjab/Mumbai", "followers_count": 65},
    {"name": "Kriti Sanon", "description": "Actress", "country": "Delhi", "followers_count": 55},
    {"name": "Madhuri Dixit", "description": "Actress", "country": "Mumbai", "followers_count": 45},
    {"name": "Kareena Kapoor", "description": "Actress", "country": "Mumbai", "followers_count": 60},

    # Global celebrities
    {"name": "Cristiano Ronaldo", "description": "Footballer", "country": "Portugal", "followers_count": 650},
    {"name": "Lionel Messi", "description": "Footballer", "country": "Argentina", "followers_count": 515},
    {"name": "Selena Gomez", "description": "Singer/Actress", "country": "USA", "followers_count": 430},
    {"name": "Kylie Jenner", "description": "Model/Entrepreneur", "country": "USA", "followers_count": 400},
    {"name": "Kim Kardashian", "description": "Entrepreneur", "country": "USA", "followers_count": 360},
    {"name": "Dwayne Johnson", "description": "Actor/Wrestler", "country": "USA", "followers_count": 390},
    {"name": "Ariana Grande", "description": "Singer", "country": "USA", "followers_count": 380},
    {"name": "Taylor Swift", "description": "Singer", "country": "USA", "followers_count": 320},
    {"name": "Beyonce", "description": "Singer", "country": "USA", "followers_count": 320},
    {"name": "Justin Bieber", "description": "Singer", "country": "Canada", "followers_count": 290},
    {"name": "Kendall Jenner", "description": "Model", "country": "USA", "followers_count": 290},
    {"name": "Khloe Kardashian", "description": "Entrepreneur", "country": "USA", "followers_count": 310},
    {"name": "Nicki Minaj", "description": "Rapper", "country": "USA", "followers_count": 230},
    {"name": "Jennifer Lopez", "description": "Singer/Actress", "country": "USA", "followers_count": 250},
    {"name": "Billie Eilish", "description": "Singer", "country": "USA", "followers_count": 120},
    {"name": "Zendaya", "description": "Actress", "country": "USA", "followers_count": 200},
    {"name": "Robert Downey Jr.", "description": "Actor", "country": "USA", "followers_count": 120},
    {"name": "Chris Hemsworth", "description": "Actor", "country": "Australia", "followers_count": 120},
    {"name": "Tom Holland", "description": "Actor", "country": "UK", "followers_count": 100},
    {"name": "Emma Watson", "description": "Actress", "country": "UK", "followers_count": 80},
    {"name": "Leonardo DiCaprio", "description": "Actor", "country": "USA", "followers_count": 60},
    {"name": "Keanu Reeves", "description": "Actor", "country": "Canada", "followers_count": 40},
    {"name": "Gal Gadot", "description": "Actress", "country": "Israel", "followers_count": 110},
    {"name": "Shakira", "description": "Singer", "country": "Colombia", "followers_count": 90},
    {"name": "Rihanna", "description": "Singer/Entrepreneur", "country": "Barbados", "followers_count": 150},
    {"name": "Ed Sheeran", "description": "Singer", "country": "UK", "followers_count": 50},
    {"name": "Miley Cyrus", "description": "Singer/Actress", "country": "USA", "followers_count": 200},
    {"name": "Drake", "description": "Rapper", "country": "Canada", "followers_count": 150},
    {"name": "Snoop Dogg", "description": "Rapper", "country": "USA", "followers_count": 90},
    {"name": "Will Smith", "description": "Actor", "country": "USA", "followers_count": 65},
    {"name": "Mark Zuckerberg", "description": "Entrepreneur", "country": "USA", "followers_count": 15},
]